export const cvData = [
  {
    name: 'Sadeem Abdulrahman Alhoshan',
    skills: 'Translation, Microsoft Word, Communication',
    age: '33',
    gender: 'female',
    nationality: 'Saudi',
    placeOfResidence: 'Riyadh',
    socialStatu: 'single',
    dateOfLastEducationalCertificate: '2018',
    lastEducationalCertificate: "Master's Degree",
    major: 'Translation',
    Courses: 'Translation Courses in Various Fields',
    yearsOfWorkExperience: '4',
    experienceLevel: 'beginner',
    expectedSalary: '0',
    dateOfPublication: '11-08-2018',
    codeReference: 'HcntlJLP',
  },
  {
    name: 'ramadan abdelaal ragab',
    skills: 'Microsoft office',
    age: '44',
    gender: 'male',
    nationality: 'Egyptian',
    placeOfResidence: 'riyadh',
    socialStatu: 'married',
    dateOfLastEducationalCertificate: '1999',
    lastEducationalCertificate: 'bachelor of arts',
    major: 'english',
    Courses: 'general diploma in education',
    yearsOfWorkExperience: '18',
    experienceLevel: 'experienced',
    expectedSalary: '0',
    dateOfPublication: '04-11-2018',
    codeReference: 'uLyNZbwD',
  },
];
